### ISSUE TITLE
Similar op code of "movl_ACC_loc32" and "pop_acc" instructions (DOC: pages 298 and 353)

### ISSUE THREAD

**Issue by SlimBenAmor** [statinf-software/tms#2] opened 2023-03-20 10:12 UTC
In this [line](https://github.com/statinf-software/tms/blob/0686007649913cecb51c26a9a7f5b303fa57a961/nmp/all.nmp#L145), I think it is ok there is no collision on the op code :
 - op code of "pop_acc": 0000 0110 1011 1110
 -  op code of "movl_ACC_loc32" : 0000 0110 LLLL LLLL, where LLLL LLLL design loc32 addressing mode (DOC: page 81-82). loc32 (LLLL LLLL) does not allow the combination "1011 1110" so there is no conflict but may be it is hard to explain this to Otawa since the two code have the same prefix.

**Comment by jordr** [comment] 2023-03-20 10:19
Thanks @SlimBenAmor for identifying the issue.
I have the solution in mind now and will implement it at some point.

**Comment by jordr** [comment] 2023-03-24 21:30
This was fixed in commits such as https://github.com/statinf-software/tms/commit/dc8003b953b7d23a975380c3e19ed0b8db855c1f

A better solution in the future should include enums, but the issue is fixed for the moment :tada:

**Closed as completed by jordr** 2023-03-24 21:30 UTC
